### ISSUE TITLE
phpunit test errors

### ISSUE THREAD

**Issue by ehsan42** [ethz-let/moodle-qtype_drawing#13]
Hi,

I have pulled the latest commits but now getting different errors when running phpunit test. not sure if helper.php has any tests as it just says No tests executed!  

<hr>
bin/moodle-docker-compose exec webserver vendor/bin/phpunit qtype_drawing_walkthrough_testcase question/type/drawing/tests/walkthrough_test.php
Moodle 3.9.11+ (Build: 20211207), 55a40f54c2b4d3b57368b41e84278e8f5f039b70
Php: 7.3.33, mysqli: 5.7.36, OS: Linux 5.4.0-91-generic x86_64
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 2.03 minutes, Memory: 54.50 MB

There was 1 error:

1) qtype_drawing_walkthrough_testcase::test_deferred_feedback_plain_text
coding_exception: Coding error detected, it must be fixed by a programmer: Invalid context id specified context::instance_by_id()

/var/www/html/lib/accesslib.php:5292
/var/www/html/question/type/drawing/renderer.php:128
/var/www/html/question/engine/renderer.php:388
/var/www/html/question/engine/renderer.php:109
/var/www/html/question/behaviour/behaviourbase.php:113
/var/www/html/question/engine/questionattempt.php:907
/var/www/html/question/engine/questionusage.php:461
/var/www/html/question/engine/tests/helpers.php:1002
/var/www/html/question/type/drawing/tests/walkthrough_test.php:47
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80
/var/www/html/vendor/phpunit/phpunit/phpunit:60

To re-run:
 vendor/bin/phpunit "qtype_drawing_walkthrough_testcase" question/type/drawing/tests/walkthrough_test.php

ERRORS!
Tests: 1, Assertions: 2, Errors: 1.

<hr>

bin/moodle-docker-compose exec webserver vendor/bin/phpunit qtype_drawing_test question/type/drawing/tests/questiontype_test.php
Moodle 3.9.11+ (Build: 20211207), 55a40f54c2b4d3b57368b41e84278e8f5f039b70
Php: 7.3.33, mysqli: 5.7.36, OS: Linux 5.4.0-91-generic x86_64
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

.F.                                                                 3 / 3 (100%)

Time: 7.16 seconds, Memory: 52.50 MB

There was 1 failure:

1) qtype_drawing_test::test_can_analyse_responses
Failed asserting that true is false.

/var/www/html/question/type/drawing/tests/questiontype_test.php:63
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80
/var/www/html/vendor/phpunit/phpunit/phpunit:60

To re-run:
 vendor/bin/phpunit "qtype_drawing_test" question/type/drawing/tests/questiontype_test.php

FAILURES!
Tests: 3, Assertions: 3, Failures: 1.

<hr>

bin/moodle-docker-compose exec webserver vendor/bin/phpunit qtype_drawing_test_helper question/type/drawing/tests/helper.php
Moodle 3.9.11+ (Build: 20211207), 55a40f54c2b4d3b57368b41e84278e8f5f039b70
Php: 7.3.33, mysqli: 5.7.36, OS: Linux 5.4.0-91-generic x86_64
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Time: 1.22 seconds, Memory: 52.50 MB

No tests executed!

**Comment by nexterday** [comment]
Hi Ehsan42, the context in the test is null -> I added a default 0 in order to complete the test. could you please try it and let me know? usually when context is null, there are invalid records in the question table(s) hence they fail.

Shall it continue this way, I'll add "skip" for the context check when in automated test mode.

**Comment by ehsan42** [comment]
questiontype_test.php is now passing but still getting the same error for walkthrough_test.php 

bin/moodle-docker-compose exec webserver vendor/bin/phpunit qtype_drawing_walkthrough_testcase question/type/drawing/tests/walkthrough_test.php
Moodle 3.9.11+ (Build: 20211207), 55a40f54c2b4d3b57368b41e84278e8f5f039b70
Php: 7.3.33, mysqli: 5.7.36, OS: Linux 5.4.0-91-generic x86_64
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 58.89 seconds, Memory: 54.50 MB

There was 1 error:

1) qtype_drawing_walkthrough_testcase::test_deferred_feedback_plain_text
coding_exception: Coding error detected, it must be fixed by a programmer: Invalid context id specified context::instance_by_id()

/var/www/html/lib/accesslib.php:5292
/var/www/html/question/type/drawing/renderer.php:128
/var/www/html/question/engine/renderer.php:388
/var/www/html/question/engine/renderer.php:109
/var/www/html/question/behaviour/behaviourbase.php:113
/var/www/html/question/engine/questionattempt.php:907
/var/www/html/question/engine/questionusage.php:461
/var/www/html/question/engine/tests/helpers.php:1002
/var/www/html/question/type/drawing/tests/walkthrough_test.php:47
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80
/var/www/html/vendor/phpunit/phpunit/phpunit:60

To re-run:
 vendor/bin/phpunit "qtype_drawing_walkthrough_testcase" question/type/drawing/tests/walkthrough_test.php

ERRORS!
Tests: 1, Assertions: 2, Errors: 1.

Im using a clean instance of moodle without any questions.

**Comment by nexterday** [comment]
OK, I added a skip block to context check when in question is unittest mode. could you please check and verify?

**Comment by ehsan42** [comment]
checked but still getting same error message.  do you get the same error when you run the test on your Moodle?

**Comment by nexterday** [comment]
Not sure why the context in your moodle is invalid, but I added a check to ignore when its missing and assigned a default value of 1. If - for whatever reason - still invalid, I'll assign a sys context to it when its missing. let me know how it goes.

**Comment by ehsan42** [comment]
invalid context gone but now getting different error

bin/moodle-docker-compose exec webserver vendor/bin/phpunit qtype_drawing_walkthrough_testcase question/type/drawing/tests/walkthrough_test.php
Moodle 3.9.11+ (Build: 20211207), 55a40f54c2b4d3b57368b41e84278e8f5f039b70
Php: 7.3.33, mysqli: 5.7.36, OS: Linux 5.4.0-91-generic x86_64
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 894 ms, Memory: 56.50 MB

There was 1 error:

1) qtype_drawing_walkthrough_testcase::test_deferred_feedback_plain_text
Trying to get property 'backgroundwidth' of non-object

/var/www/html/question/type/drawing/renderer.php:137
/var/www/html/question/engine/renderer.php:388
/var/www/html/question/engine/renderer.php:109
/var/www/html/question/behaviour/behaviourbase.php:113
/var/www/html/question/engine/questionattempt.php:907
/var/www/html/question/engine/questionusage.php:461
/var/www/html/question/engine/tests/helpers.php:1002
/var/www/html/question/type/drawing/tests/walkthrough_test.php:47
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80
/var/www/html/vendor/phpunit/phpunit/phpunit:60

To re-run:
 vendor/bin/phpunit "qtype_drawing_walkthrough_testcase" question/type/drawing/tests/walkthrough_test.php

ERRORS!
Tests: 1, Assertions: 2, Errors: 1

**Comment by nexterday** [comment]
those errors actually show that records in the db are incorrect/missing and thats likely due to previous errors where some transactions were halted and part of data was already logged. unfortunately, if errors persist, you may need to fresh-install it or avoid dockers because all fixes are technically workarounds to get your dockers unittest pass.

**Comment by ehsan42** [comment]
Yes seems to be my local setup and I've ran the rest on our separate development pipeline and the test are passing fine.  So that's fine we can leave it at that.  Thanks.

**Comment by ehsan42** [comment]
Yes seems to be my local setup as I've ran the tests on our separate development pipeline and the test are passing fine.  So that's fine we can leave it at that.  Thanks.

**Comment by ehsan42** [comment]
I've ran the test on a team development pipeline and again on my local setup and getting the following error.  I deleted my local Moodle and installed fresh with clean database but still getting error.  We're setup with docker so cant avoid.  

qtype_drawing_walkthrough_testcase::test_deferred_feedback_plain_text
Questions is in the wrong state.
question_state_todo Object &0000000032105f00000000005994df72 () is not instance of expected class "question_state_complete".
--- Expected
+++ Actual
@@ @@
-question_state_complete Object &0000000032105f06000000005994df72 ()
+question_state_todo Object &0000000032105f00000000005994df72 ()

/var/www/html/question/engine/tests/helpers.php:889
/var/www/html/question/type/drawing/tests/walkthrough_test.php:51
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80
/var/www/html/vendor/phpunit/phpunit/phpunit:60

**Comment by nexterday** [comment]
Hi, we consider empty answer as an answer - aka complete, however, seems unittest consider them as yet todo. I'll change it to todo in the test, but please consider that a real attempt would still be marked as complete.
