### ISSUE TITLE
Feature request: extended drawing tool (rectangle, circle, ...)

### ISSUE THREAD

**Issue by AntonT76** [ethz-let/moodle-qtype_drawing#17]
Hi,

great plugin - thank you!

I would like to make a feature request regarding an extended drawing tool: in addition to the existing text and line drawing tool it would be nice if there is also a possibilty to draw rectangles, circles, ... (I would like to contribute a solution, but unfortunately I don't have programming skills).

br, Anton

**Comment by nexterday** [comment]
Hi Anton, 
if you go to /admin/settings.php?section=qtypesettingdrawing
you can let teacher allow advanced mode - we have hidden this feature because its not fully tested - feel free to pilot it until we fully test it (and fix whatever bugs we encounter).
cheers

**Comment by AntonT76** [comment]
Dear @nexterday,
thank you for your quick reply. Sorry, I didn't see that setting ... now it works. Yes, great - that's exactly what I was looking for.

br Anton
