### ISSUE TITLE
Failed Behat tests

### ISSUE THREAD

**Issue by dragos5436** [ethz-let/moodle-qtype_drawing#18]
Hi,

There are a few Behat tests failing for this plugin:

1. /var/www/html/question/type/drawing/tests/behat/add.feature:21
   Feature: Test creating an drawing question
   Scenario: Create an drawing question with Response format set to 'HTML editor'
```
And I navigate to "Question bank" node in "Course administration"
```

2. /var/www/html/question/type/drawing/tests/behat/backup_and_restore.feature:30
   Feature: Test duplicating a quiz containing an drawing question
   Scenario: Backup and restore a course containing 3 drawing questions
```
And I navigate to "Question bank" node in "Course administration"
```

3. /var/www/html/question/type/drawing/tests/behat/edit.feature:29
   Feature: Test editing an drawing question
   Scenario: Edit an drawing question
```
And I navigate to "Question bank" node in "Course administration"
```

4. /var/www/html/question/type/drawing/tests/behat/export.feature:28
   Feature: Test exporting drawing questions
   Scenario: Export 3 drawing questions
```
When I navigate to "Export" node in "Course administration > Question bank"
```

5. /var/www/html/question/type/drawing/tests/behat/import.feature:21
   Feature: Test importing drawing questions
   Scenario: import drawing question.
```
When I navigate to "Import" node in "Course administration > Question bank"
```

MySQL 5.7
PHP 7.4
Moodle latest MOODLE_400_STABLE
executed with moodlehq/moodle-docker

**Comment by AdilIqbal95** [comment]
Also failing on Moodle 311

**Comment by nexterday** [comment]
@spillinge hier auch bitte. Danke!

**Comment by lucaboesch** [comment]
@spillinge @nexterday this can probably be closed with your latest commits.
