### ISSUE TITLE
Exception - Call to undefined method qtype_drawing_edit_form::get_default_value()

### ISSUE THREAD

**Issue by ratnavis** [ethz-let/moodle-qtype_drawing#19]
We get the above error opening drawings.

The stack trace shows (typed from a screen-shot):
line 118 of /question/type/drawingP/edit_drawing_form.php Error thrown
line 214 of /lib/formslib.php: call to qtype_drawing_edit_form->definition()
link 113 of /question/type/edit_question_form.php: call to moodleform->__construct()
line 217 of /question/type/questiontypebase.php: call to question_edit_form->__construct()
line 202 of /question/question.php: call to question_type->create_editing_form()

Moodle 3.9.16 (Build: 20220822)

$plugin->version = 2022040600;
$plugin->requires = 2020052000; // Moodle >=3.9.

$plugin->maturity = MATURITY_STABLE;
$plugin->release = '4 for Moodle 3.9+ (Transitional)';

**Comment by nexterday** [comment]
The version you are using needs to be updated, a lot of transitional changes happened since then. 

For any moodle version below 3.11, you should use the last supported plugin for “old” moodle versions. You can find it here: https://github.com/ethz-let/moodle-qtype_drawing/releases/tag/final-release-3.x

**Comment by ratnavis** [comment]
Hi, thanks for the prompt reaction with solution! I replaced the /drawing with the content of the zip. Moodle complained about downgrading. I've set $plugin->version = 2022122700; to override it. Hope, I won't run out of version numbers when the final version is released. ;) BTW, teachers are testing their quizzes. Will update here once I get their confirmation.
