### ISSUE TITLE
Release tag matching the public release (2020111800) is missing

### ISSUE THREAD

**Issue by matsimon** [ethz-let/moodle-qtype_drawing#3]
Hi

We wanted to install this nice plugin of yours in our Moodle instance at our school using git directly but I saw that the git tags and releases on this Github repository as referenced on the Moodle plugins site didn't match. Also some releases on your github repo clearly mention that they are for internal use at ETH LET only.

I've tried to find which git tag corresponds with the public release, but was unable to do so within reasonable time, the diff is pretty big between all git tags and the public release remain rather large. Is anything I can do for you to get this tag matching with the publicly released ZIP archive on moodle.org?

Regards
Mathieu

**Comment by nexterday** [comment]
Dear Mathieu, we strongly recommend you use the master branch for the latest fixes. We are actively changing in the plugin hence the major log. If you want to use per release, please download it directly from our github:  https://github.com/ethz-let/moodle-qtype_drawing/tree/0.3

we are sorry about that, but we have had a flood of requests and not before end of March 2021 to see a stable branching as we maintain private and public branches and we plan to merge them as soon as we are confident about the major updates (which requires intensive testing beforehand)

**Comment by matsimon** [comment]
Hi

Thank you very much for your kind and prompt answer (that was super prompt!), I can definitely understand your decision.
As you can see, your work is gets appreciated outside of ETH :-)

Concerning your strong recommendation: Wouldn't it be useful to have that note also on the respective Moodle plugin site, so that you end up with users using your recommended release or code branch?

Best Regards,
Mathieu

**Comment by nexterday** [comment]
Thanks Mathieu, your nice words empower us. We actually do a regular monthly (or per milestone) update on moodle.org. Reason of no update for Jan is we are adding major features and enhancements to FHD so we are waiting until they go through the cycle to make an update on moodle in order to reduce potential confusion/risk.

thanks again and stay tuned :-)
