### ISSUE TITLE
Deprecated array_key_exists()

### ISSUE THREAD

**Issue by lucaboesch** [ethz-let/moodle-qtype_drawing#4]
In newer versions, with a high debug level, Moodle triggers a

Deprecated:  array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in …/question/type/drawing/edit_drawing_form.php on line 192

Warning.

Best,
Luca

**Comment by nexterday** [comment]
Thanks Luca, it will be added to the next release and fixed on master.
